### ISSUE TITLE
Directory of Sheet Music

### ISSUE THREAD

**Issue by tienne-B** [cellist/Lilypond-Sheet-Music#1]
It would be helpful to have a list of the songs included in the repo. Thanks for all the songs!

**Comment by ghost** [comment]
I've made [mkcatalogue.sh](https://gist.github.com/mengele-chan/385797b9162d77397a4c) for this purpose. It creates two Markdown-formatted files:
- `compositions.md` which contains a list of id's, titles, subtitles and composers;
- `paths.md` which contains a list of id's with paths.
