### ISSUE TITLE
Great project !

### ISSUE THREAD

**Issue by edi9999** [cellist/Lilypond-Sheet-Music#2]
Just wanted to let you know that I have been searching for solo cello music, and I finally found this !

It really looks good. 

I will let you know what I think about it.

**Comment by cellist** [comment]
Merci, Edgar! Nice to hear you like it!

**Comment by edi9999** [comment]
Yes, I have enjoyed the demoivre first suite for example : https://github.com/cellist/Lilypond-Sheet-Music/blob/master/Vlc/Demoivre%2C%20Daniel/Cellosuite%201/demoivre_cello_suite_1.pdf

:-)
