### ISSUE TITLE
Morricone/Gabriels Oboie seems to have wrong transpose statement for Englisch Horn track

### ISSUE THREAD

**Issue by molleJoe** [cellist/Lilypond-Sheet-Music#3]
Sadly there seems to be a wrong transpose statement
~~~
\transpose d a,
~~~
But easy to clean up:
~~~
diff --git a/Orchestra/Morricone, Ennio/Gabriels Oboe/morricone_gabriels_oboe.ly b/Orchestra/Morricone, Ennio/Gabriels Oboe/morricone_gabriels_oboe.ly
index 8b2830ea..fb759b71 100644
--- a/Orchestra/Morricone, Ennio/Gabriels Oboe/morricone_gabriels_oboe.ly
+++ b/Orchestra/Morricone, Ennio/Gabriels Oboe/morricone_gabriels_oboe.ly
@@ -45,7 +45,7 @@ music = \new StaffGroup <<
       \new Staff {
         \set Staff.midiInstrument = \mihi
         \set Staff.instrumentName = \markup \center-column { "Englisch" "Horn" }
-        \transpose d a, { \va }
+        \transpose a a { \va }
       }

       \new Staff {
~~~

Remark: pdf is wrong, too. Should be created by cleaned ly file.

Remark: Thank you for your scores!

**Comment by cellist** [comment]
I am sorry, it took me two years to read about your issue, I apologize!
Not only has Ennio Morricone died, but also my dear friend who played the English Horn.
Her instrument actually has this "offset" from my instrument, the cello, so for her the notation was correct.
You will see this "offset" also in the other sheet music which involves the English Horn.
But please feel free to adapt your version!

You can also check [Wikipedia](https://en.wikipedia.org/wiki/Cor_anglais) on this.
